-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 08:29:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gimDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gimDB` ;

-- -----------------------------------------------------
-- Schema gimDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gimDB` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `gimDB` ;

-- -----------------------------------------------------
-- Table `gimDB`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gimDB`.`city` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gimDB`.`city` (

  `idcity` BIGINT UNSIGNED AUTO_INCREMENT,
  `namecity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcity`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `gimDB`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gimDB`.`sede` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gimDB`.`sede` (
  `idsede` BIGINT UNSIGNED AUTO_INCREMENT,
  `city_idcity` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsede`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_sede_city1_idx` ON `gimDB`.`sede` (`city_idcity` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `gimDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gimDB`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gimDB`.`user` (
  `iduser` BIGINT UNSIGNED AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `role` enum('admin','client') ,
  `sede_idsede` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iduser`, `sede_idsede`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `gimDB`.`user` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_user_sede` ON `gimDB`.`user` (`sede_idsede` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



